wandb_version: 1

lr:
  desc: null
  value: 1.0e-05
n_epochs:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 8
model_name:
  desc: null
  value: distilbert-base-uncased
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.45.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729695399.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.4
      6: 4.45.0
      8:
      - 3
      - 5
      13: windows-amd64
